language: objective-c
osx_image: xcode8
branches:
  only:
    - dev
script:
- if [ $MODE == 'Tests' ]; then set -o pipefail && xcodebuild -workspace nubecero.xcworkspace -scheme nubecero -sdk "iphonesimulator" -destination "platform=iOS Simulator,OS=10.0,name=iPhone 6s" clean build test | xcpretty; fi
- if [ $MODE == 'Build' ]; then set -o pipefail && xcodebuild -workspace nubecero.xcworkspace -scheme nubecero -sdk "iphonesimulator" -destination "platform=iOS Simulator,OS=10.0,name=iPhone 6s" clean build | xcpretty; fi
notifications:
  email:
    on_success: never
    on_failure: never
env:
  matrix:
  - MODE=Tests
  - MODE=Build
